apiVersion: v1
kind: Service
metadata:
  name: galaxy-bce
  namespace: galaxy-web
  labels:
    app: galaxy-bce
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: galaxy-bce
  sessionAffinity: None

